'use client'

import Link from 'next/link'
import { ArrowRight, Check, Coins, Flame, Menu, Sparkles, Target, Trophy, X, Zap } from 'lucide-react'
import { useState } from 'react'
import { useGame } from '@/lib/game-context'
import { DashboardPage } from '@/components/dashboard-page'

export default function HomePage() { const { account } = useGame(); return account ? <DashboardPage /> : <LandingPage /> }

function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const features = [[Target, 'QUESTS', 'Turn everyday responsibilities into clear objectives.'], [Zap, 'XP & LEVELS', 'See yourself progress as you complete meaningful work.'], [Flame, 'HABITS & STREAKS', 'Build consistency and maintain momentum.'], [Coins, 'REWARDS', 'Exchange earned Gold for rewards you actually want.'], [Trophy, 'ACHIEVEMENTS', 'Create milestones that recognize your progress.'], [Sparkles, 'PERSONAL STATS', 'Understand how you are growing over time.']] as const
  const steps = [['01', 'CREATE', 'Turn something you want to accomplish into a task.'], ['02', 'COMPLETE', 'Finish the task in real life.'], ['03', 'PROGRESS', 'Earn XP, Gold and streak momentum.'], ['04', 'REWARD', 'Use your Gold for something meaningful.']]
  const rewards = [['☕', 'Coffee Break', '100 Gold'], ['🎬', 'Movie Night', '300 Gold'], ['🎮', 'Gaming Session', '500 Gold'], ['🍕', 'Favorite Meal', '800 Gold']]
  return <main className="min-h-dvh overflow-hidden bg-background">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground shadow-[0_8px_30px_-8px_var(--violet)]"><Sparkles className="size-5" /></span><span className="font-display text-xl font-bold tracking-tight">LifeQuest</span></Link><div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#features" className="hover:text-foreground">Features</a><a href="#how-it-works" className="hover:text-foreground">How It Works</a><a href="#rewards" className="hover:text-foreground">Rewards</a><a href="#progress" className="hover:text-foreground">Progress</a></div><div className="hidden items-center gap-3 md:flex"><Link href="/login" className="rounded-xl px-4 py-2.5 text-sm font-semibold text-muted-foreground hover:text-foreground">Log in</Link><Link href="/signup" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Sign up</Link></div><button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></nav>
    {menuOpen && <div className="mx-5 grid gap-3 rounded-2xl border border-white/10 bg-white/[.04] p-4 md:hidden"><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How It Works</a><Link href="/login">Log in</Link><Link href="/signup" className="text-primary">Sign up</Link></div>}
    <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pt-16 pb-24 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:pt-24"><div className="absolute top-0 right-1/4 size-96 rounded-full bg-primary/15 blur-[110px]" /><div className="relative"><p className="mb-5 flex items-center gap-2 text-xs font-semibold tracking-[.25em] text-[var(--gold)] uppercase"><span className="size-2 rounded-full bg-[var(--gold)]" /> A calmer way to grow</p><h1 className="max-w-2xl font-display text-5xl font-bold leading-[1.02] tracking-[-.04em] sm:text-7xl">Your Life.<br /><span className="text-gradient">Your Progress.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Turn everyday actions into meaningful progress. Complete what matters, earn XP, build streaks, and use Gold to reward yourself.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/signup" className="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground">Start your journey <ArrowRight className="size-4" /></Link><a href="#how-it-works" className="inline-flex h-12 items-center rounded-xl border border-white/10 bg-white/[.04] px-5 font-semibold">See how it works</a></div><div className="mt-8 flex items-center gap-6 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-4 text-[var(--success)]" /> Real progress</span><span className="flex items-center gap-2"><Check className="size-4 text-[var(--success)]" /> No noise</span></div></div><Preview /></section>
    <section id="how-it-works" className="border-y border-white/8 bg-white/[.025] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="The core loop" title="Make progress tangible." text="LifeQuest gives the things you already care about a clear, rewarding shape." /><div className="relative mt-12 grid gap-8 md:grid-cols-4">{steps.map(([num, title, text]) => <div key={num}><span className="font-display text-sm text-primary">{num}</span><h3 className="mt-4 font-display font-bold tracking-wide">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><SectionIntro eyebrow="Built for consistency" title="A system that respects your attention." text="Everything you need to turn intention into a visible rhythm." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text]) => <div key={title} className="glass rounded-2xl p-6"><span className="grid size-11 place-items-center rounded-xl bg-primary/15 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 font-display font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>
    <section id="rewards" className="border-y border-white/8 bg-[#171124] px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-3 text-xs font-semibold tracking-[.25em] text-[var(--gold)] uppercase">The Gold system</p><h2 className="font-display text-4xl font-bold tracking-tight sm:text-5xl">Earn it. Save it.<br /><span className="text-[var(--gold)]">Reward yourself.</span></h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Every completed task can earn Gold. Save it for something that actually matters to you.</p></div><div className="grid gap-3 sm:grid-cols-2">{rewards.map(([icon, name, cost]) => <div key={name} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-4"><span className="text-2xl">{icon}</span><div><p className="font-display font-bold">{name}</p><p className="mt-1 text-xs text-[var(--gold)]">{cost}</p></div></div>)}</div></div></section>
    <section id="progress" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><SectionIntro eyebrow="Visible momentum" title="There is always another level." text="Consistent progress unlocks new levels, achievements and collectible Life Cards." /><div className="mt-12 grid gap-3 md:grid-cols-4">{[['12', 'CURRENT', '2,450 / 3,000 XP'], ['13', 'FOCUSED MIND', 'Consistency creates clarity.'], ['14', 'DISCIPLINE', 'Show up even when motivation doesn’t.'], ['15', 'ELITE CONSISTENCY', 'Small actions. Extraordinary results.']].map(([level, title, detail], i) => <div key={level} className={`rounded-2xl border p-5 ${i === 0 ? 'border-primary/40 bg-primary/10' : 'border-white/10 bg-white/[.03]'}`}><span className="text-xs font-semibold tracking-[.2em] text-primary">LEVEL {level}</span><h3 className="mt-4 font-display text-lg font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{detail}</p></div>)}</div></section>
    <section className="mx-5 mb-20 rounded-[2rem] border border-primary/20 bg-gradient-to-br from-primary/20 via-white/[.04] to-[var(--gold)]/10 px-6 py-16 text-center sm:mx-8"><h2 className="font-display text-4xl font-bold tracking-tight sm:text-5xl">Start making progress<br /><span className="text-gradient">you can see.</span></h2><p className="mx-auto mt-4 max-w-md text-muted-foreground">Your next level starts with one task.</p><Link href="/signup" className="mt-8 inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-6 font-semibold text-primary-foreground">Start your journey <ArrowRight className="size-4" /></Link></section>
    <footer className="border-t border-white/8 px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 sm:flex-row"><div><p className="font-display text-lg font-bold">LifeQuest</p><p className="mt-2 text-sm text-muted-foreground">Your Life. Your Progress.</p></div><div className="flex gap-8 text-sm text-muted-foreground"><div><p className="mb-3 font-semibold text-foreground">Product</p><a href="#features" className="block hover:text-foreground">Features</a><a href="#rewards" className="mt-2 block hover:text-foreground">Rewards</a></div><div><p className="mb-3 font-semibold text-foreground">Account</p><Link href="/login" className="block hover:text-foreground">Log in</Link><Link href="/signup" className="mt-2 block hover:text-foreground">Sign up</Link></div></div></div></footer>
  </main>
}

function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="max-w-xl"><p className="mb-3 text-xs font-semibold tracking-[.25em] text-primary uppercase">{eyebrow}</p><h2 className="font-display text-4xl font-bold tracking-tight">{title}</h2><p className="mt-4 leading-7 text-muted-foreground">{text}</p></div> }
function Preview() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute inset-0 rounded-[2rem] bg-primary/20 blur-3xl" /><div className="glass-strong relative overflow-hidden rounded-[2rem] p-5 shadow-[0_30px_100px_-35px_var(--violet)]"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Sparkles className="size-4" /></span><span className="font-display font-bold">LifeQuest</span></div><span className="text-xs text-[var(--success)]">● On track</span></div><div className="grid gap-3 py-5 sm:grid-cols-3"><div className="rounded-xl bg-primary/10 p-3"><p className="text-xs text-muted-foreground">Level</p><p className="mt-1 font-display text-2xl font-bold">12</p></div><div className="rounded-xl bg-[var(--gold)]/10 p-3"><p className="text-xs text-muted-foreground">Gold</p><p className="mt-1 font-display text-2xl font-bold text-[var(--gold)]">1,840</p></div><div className="rounded-xl bg-[var(--success)]/10 p-3"><p className="text-xs text-muted-foreground">Streak</p><p className="mt-1 font-display text-2xl font-bold text-[var(--success)]">12d</p></div></div><div className="rounded-xl border border-white/10 p-4"><div className="flex justify-between text-sm"><span className="font-semibold">Today&apos;s progress</span><span className="text-muted-foreground">2 / 5</span></div><div className="mt-3 h-2 rounded-full bg-white/10"><span className="block h-full w-2/5 rounded-full bg-primary" /></div>{['Study DSA', 'Morning workout', 'Read 20 pages'].map((task, i) => <div key={task} className="mt-4 flex items-center gap-3 text-sm"><span className={`grid size-5 place-items-center rounded-full border ${i === 1 ? 'border-[var(--success)] bg-[var(--success)] text-background' : 'border-white/20'}`}>{i === 1 && <Check className="size-3" />}</span><span className={i === 1 ? 'text-muted-foreground line-through' : ''}>{task}</span></div>)}</div></div></div> }
